import React from "react";

export default function About() {
    return (
        <div className="container">
            <h1>About</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consectetur lorem donec massa sapien faucibus. Nunc mi ipsum faucibus vitae aliquet nec. Nec ullamcorper sit amet risus nullam eget felis. Augue neque gravida in fermentum. Varius quam quisque id diam. Diam sollicitudin tempor id eu nisl nunc mi. Placerat in egestas erat imperdiet sed. Montes nascetur ridiculus mus mauris vitae ultricies leo. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim lobortis. Enim ut sem viverra aliquet eget sit amet tellus cras. Lacinia at quis risus sed. Elementum integer enim neque volutpat ac. A erat nam at lectus urna duis convallis. Metus aliquam eleifend mi in nulla posuere. Dapibus ultrices in iaculis nunc sed augue lacus viverra. Senectus et netus et malesuada fames ac turpis egestas. Facilisis mauris sit amet massa.

                Cursus metus aliquam eleifend mi. Id faucibus nisl tincidunt eget nullam non. Id eu nisl nunc mi ipsum. Tortor condimentum lacinia quis vel eros donec ac. Eu consequat ac felis donec et odio pellentesque diam. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed velit. Tellus integer feugiat scelerisque varius morbi enim nunc faucibus a. Pellentesque habitant morbi tristique senectus et. Cursus in hac habitasse platea dictumst quisque sagittis purus sit. Praesent tristique magna sit amet purus gravida quis. Diam quam nulla porttitor massa id. Netus et malesuada fames ac. Ultricies lacus sed turpis tincidunt id aliquet risus feugiat in. Purus sit amet volutpat consequat mauris. Dolor sit amet consectetur adipiscing. Nec nam aliquam sem et tortor. Lacus vel facilisis volutpat est. Neque aliquam vestibulum morbi blandit cursus risus at ultrices mi.

                Sed sed risus pretium quam vulputate dignissim. Ultricies mi quis hendrerit dolor. Vivamus at augue eget arcu dictum varius. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Neque convallis a cras semper auctor neque. Amet mauris commodo quis imperdiet massa. Lobortis mattis aliquam faucibus purus in. Ut faucibus pulvinar elementum integer. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero nunc. Quam vulputate dignissim suspendisse in est ante in nibh. Leo duis ut diam quam nulla porttitor massa id. Suspendisse ultrices gravida dictum fusce ut placerat orci nulla pellentesque. Amet venenatis urna cursus eget nunc scelerisque viverra. Vel risus commodo viverra maecenas accumsan. In massa tempor nec feugiat nisl pretium fusce id velit.

                Fringilla phasellus faucibus scelerisque eleifend donec pretium. Orci eu lobortis elementum nibh tellus. Lorem ipsum dolor sit amet consectetur adipiscing elit. Sed faucibus turpis in eu mi bibendum neque. Amet volutpat consequat mauris nunc congue. Sem fringilla ut morbi tincidunt augue interdum. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Viverra aliquet eget sit amet tellus cras. Et netus et malesuada fames ac turpis egestas sed tempus. Quam nulla porttitor massa id neque. Eget mi proin sed libero enim. Lorem donec massa sapien faucibus et molestie. Purus in mollis nunc sed id semper. Gravida rutrum quisque non tellus orci ac auctor augue. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus.

                Bibendum est ultricies integer quis auctor. Eu sem integer vitae justo eget magna fermentum. Iaculis urna id volutpat lacus laoreet non curabitur gravida. Quam vulputate dignissim suspendisse in est. Arcu felis bibendum ut tristique et egestas quis ipsum. Mattis pellentesque id nibh tortor id aliquet lectus proin nibh. Sit amet massa vitae tortor. Dolor morbi non arcu risus quis varius quam. Nibh tellus molestie nunc non blandit massa enim. Vulputate sapien nec sagittis aliquam malesuada. Etiam tempor orci eu lobortis elementum nibh. Aliquam vestibulum morbi blandit cursus risus at ultrices. Penatibus et magnis dis parturient montes nascetur ridiculus mus mauris. Et sollicitudin ac orci phasellus egestas tellus.</p>
        </div>
    )
}