name: deploy production
on:
  push:
    branches: [main]

jobs:
  job_one:
    name: deploy
    runs-on: ubuntu-latest
    steps:

    - name: Deploy blog update
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.SSH_HOST}}
        username: ${{secrets.SSH_USERNAME}}
        password: ${{secrets.ID_RSA_GITHUB_FRONTEND}}
        port: 2222
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          pm2 stop blog
          cd /home/agarcia/portfolioBlog_frontEnd
          git fetch
          git pull
          git status
          npm run build
          pm2 start blog
