name: deploy production
on:
  push:
    branches: [main]

jobs:
  job_one:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: test SSH connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.SSH_HOST}}
        username: ${{secrets.SSH_USERNAME}}
        password: ${{secrets.ID_RSA_GITHUB_FRONTEND}}
        port: 22
        script: |
          cd /home/agarcia/portfolioBlog_frontEnd
          git pull origin main
          git status