name: deploy production
on:
  push:
    branches: [main]

  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: deploy source-code
      uses: appleboy/scp-action@master
      env:
        HOST: ${{secrets.SSH_HOST}}
        USERNAME: ${{secrets.SSH_USERNAME}}
        PORT: 22
        KEY: ${{secrets.ID_RSA_GITHUB_FRONTEND}}
      with:
        source: "*"
        target: "/home/agarcia/portfolioBlog_frontEnd"